ALTER TABLE rutas ADD COLUMN precio DECIMAL(10,2) NOT NULL DEFAULT 0.00;
ALTER TABLE rutas ADD COLUMN capacidad INT DEFAULT 14;
ALTER TABLE rutas ADD COLUMN hora_salida TIME;
ALTER TABLE rutas ADD COLUMN hora_llegada TIME;
